---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - k8smanageers.greyridge.com
  resources:
  - workloadmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8smanageers.greyridge.com
  resources:
  - workloadmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - k8smanageers.greyridge.com
  resources:
  - workloadmanagers/status
  verbs:
  - get
  - patch
  - update
