# permissions for end users to view workloadmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workloadmanager
    app.kubernetes.io/managed-by: kustomize
  name: workloadmanager-viewer-role
rules:
- apiGroups:
  - k8smanageers.greyridge.com
  resources:
  - workloadmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8smanageers.greyridge.com
  resources:
  - workloadmanagers/status
  verbs:
  - get
