apiVersion: apps/v1
kind: Deployment
metadata:
  name: central
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central
  template:
    metadata:
      labels:
        app: central
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - centralblue
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80