apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workloadmanager.fullname" . }}-controller-manager
  labels:
  {{- include "workloadmanager.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}