name: Docker Build and Publish
on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'bugfix/*'
jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker Image Tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
            echo "IMAGE_TAG=${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/workload-manager:${{ env.IMAGE_TAG }}
  helm-upload:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Chart
        working-directory: charts/workloadmanager
        run: |
          helm package .

      - name: Helm Index
        working-directory: charts/workloadmanager
        run: |
          curl -o remote-index.yaml https://k8smanagers.blob.core.windows.net/helm/index.yaml 
          helm repo index --merge remote-index.yaml .

      - name: Helm Upload
        working-directory: charts/workloadmanager
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          az storage blob upload --container-name helm --file index.yaml --name index.yaml --overwrite
          az storage blob upload --container-name helm --file *.tgz --name *.tgz --overwrite